name: macOS CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Homebrew dependencies
      run: brew install cmake glfw glm
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G Xcode
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: xcodebuild -project GeoLEDic.xcodeproj -target ALL_BUILD
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: xcodebuild -project GeoLEDic.xcodeproj -target RUN_TESTS
